name: GitLeaks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "30 18 * * 5"

permissions:
  contents: read
  security-events: write

jobs:
  git-leaks:
    permissions:
      contents: read
      security-events: write
    name: GitLeaks
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
